var lang = {
    "en": {
        'JMATIC': 'jMatic',
        'TITLE_DEVICE_STATE': 'Device State',
        'TITLE_DEVICE_STATE_EDIT': 'Edit Device State',
        'TITLE_DEVICE_CONFIG': 'Subscription Config',
        'TITLE_BATTERY_CHECK': 'Battery Check',
        'TITLE_SYSVARS': 'System Variables',
        'TITLE_APP_CONFIG': 'Settings',
        'BUTTON_LANG_DE': 'de',
        'BUTTON_LANG_EN': 'en',
        'APP_CONFIG_LANGUAGE': 'Language ',
        'NAME': 'Name',
        'TYPE': 'Type',
        'SHOW_NAMES': 'Show Names',
        'HIDE_NAMES': 'Hide Names',
        'STACK_LAYOUT': 'Stack Layout',
        'FLOW_LAYOUT': 'Flow Layout',
        'MENU': 'Menu',
    },
    "de": {
        'TITLE_DEVICE_STATE': 'Gerätestatus',
        'TITLE_DEVICE_STATE_EDIT': 'Gerätestatus ändern',
        'TITLE_DEVICE_CONFIG': 'Abo-Konfiguration',
        'TITLE_BATTERY_CHECK': 'Batteriecheck',
        'TITLE_SYSVARS': 'Systemvariablen',
        'TITLE_APP_CONFIG': 'Einstellungen',
        'APP_CONFIG_LANGUAGE': 'Sprache ',
        'NAME': 'Name',
        'TYPE': 'Typ',
        'SHOW_NAMES': 'Mit Namen',
        'HIDE_NAMES': 'Ohne Namen',
        'STACK_LAYOUT': 'Tabellarisch',
        'FLOW_LAYOUT': 'Fließend',
        'MENU': 'Menü',
    }
};