"use strict";

var lang = {
    "en": {
        'JMATIC': 'jMatic',
        'TITLE_DEVICE_STATE': 'Device State',
        'TITLE_DEVICE_STATE_EDIT': 'Edit Device State',
        'TITLE_DEVICE_CONFIG': 'Subscription Config',
        'TITLE_BATTERY_CHECK': 'Battery Check',
        'TITLE_SYSVARS': 'System Variables',
        'TITLE_PROGRAMS': 'Programs',
        'TITLE_APP_CONFIG': 'Settings',
        'BUTTON_LANG_DE': 'de',
        'BUTTON_LANG_EN': 'en',
        'APP_CONFIG_LANGUAGE': 'Language ',
        'APP_CONFIG_DEVICESTATERELOADINTERVAL': 'Device state reload interval (seconds)',
        'NAME': 'Name',
        'TYPE': 'Type',
        'SHOW_NAMES': 'Show Names',
        'HIDE_NAMES': 'Hide Names',
        'STACK_LAYOUT': 'Stack Layout',
        'FLOW_LAYOUT': 'Flow Layout',
        'MENU': 'Menu',
        'LEGEND': 'Legend',
        'DEVICE_DELETE': 'Delete device in jMatic',
        'DEVICE_CONFIG_MISSING_ON_CCU': 'Device configuration is missing on your CCU (device was probably deleted there!)',
        'DEVICE_CONFIG_SYNCHRONIZE': 'Synchronize device configuration in jMatic with your devices registered on your CCU',
        'DEVICE_REGISTERED': 'Device is registered in jMatic',
        'DETAILS': 'Details',
        'ID': 'Id',
        'DESCRIPTION': 'Description',
        'ERROR': 'Error',
        'SUCCESS': 'Success',
    },
    "de": {
        'TITLE_DEVICE_STATE': 'Gerätestatus',
        'TITLE_DEVICE_STATE_EDIT': 'Gerätestatus ändern',
        'TITLE_DEVICE_CONFIG': 'Abo-Konfiguration',
        'TITLE_BATTERY_CHECK': 'Batteriecheck',
        'TITLE_SYSVARS': 'Systemvariablen',
        'TITLE_PROGRAMS': 'Programme',
        'TITLE_APP_CONFIG': 'Einstellungen',
        'APP_CONFIG_LANGUAGE': 'Sprache ',
        'APP_CONFIG_DEVICESTATERELOADINTERVAL': 'Gerätestatus Aktualisierungs-Intervall (Sekunden)',
        'NAME': 'Name',
        'TYPE': 'Typ',
        'SHOW_NAMES': 'Mit Namen',
        'HIDE_NAMES': 'Ohne Namen',
        'STACK_LAYOUT': 'Tabellarisch',
        'FLOW_LAYOUT': 'Fließend',
        'MENU': 'Menü',
        'LEGEND': 'Legende',
        'DEVICE_DELETE': 'Konfiguration in jMatic löschen',
        'DEVICE_CONFIG_MISSING_ON_CCU': 'Geräte-Konfiguration fehlt auf deiner CCU-Zentrale (Gerät wurde wahrscheinlich dort gelöscht!)',
        'DEVICE_CONFIG_SYNCHRONIZE': 'Geräte-Konfigurationen in jMatic mit den Konfiguration auf der CCU-Zentrale synchronisieren',
        'DEVICE_REGISTERED': 'Gerät ist in jMatic registriert',
        'DESCRIPTION': 'Beschreibung',
        'ERROR': 'Fehler',
        'SUCCESS': 'Erfolgreich',
    }
};